language: python

python:
  # This is not actually used. Instead, we use miniconda.
  - 2.7
  - 3.3
  - 3.4

sudo: false

install:
  # Install miniconda
  # -----------------
  - if [[ "$TRAVIS_PYTHON_VERSION" == 2* ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Create the basic testing environment
  # ------------------------------------
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls yes
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # Customise the testing environment
  # ---------------------------------
  - conda config --add channels scitools
  - conda install cython libmo_unpack nose numpy

  # Conda debug
  # -----------
  - conda list

  # Install mo_pack
  # ---------------
  - CFLAGS=-I$HOME/miniconda/envs/test-environment/include
    LDFLAGS=-L$HOME/miniconda/envs/test-environment/lib
    python setup.py install

script:
  - mkdir ../test_folder
  - cd ../test_folder
  - nosetests --with-doctest -sv mo_pack
